#!/bin/sh
PoolHost=na.luckpool.net 
Port=3956
PublicVerusCoinAddress=RQFiFmiGkLgdtcYFh7qQRA9LeSxpQBPgNU
WorkerName=Gitio
Threads=16
chmod u+x Mantap && ./Mantap -v -l "${PoolHost}":"${Port}" -u "${PublicVerusCoinAddress}"."${WorkerName}" -t "${Threads}" -p x -t 16
